#!/usr/bin/env bash

set -eu
set -o pipefail
shopt -s nocasematch
export PYTHONIOENCODING=utf8

if ! command -v "termgraph" > /dev/null; then
  echo "Error: Could not find required command 'termgraph'"
  exit 1
fi

function query() {
  local CURL_RESULT=0
  NOW=$(python -c 'from time import time; print int(round(time() * 1000))')
  CURL_TIMINGS=$(curl -o /dev/null -D /tmp/springmeyer-viz.log -k -H 'Cache-Control: no-cache' -L -w 'client:dns-lookup %{time_namelookup}|client:tls-handshake %{time_appconnect}|client:ttfb %{time_starttransfer}' -Sfs "${1}") || CURL_RESULT=$?
  ELAPSED=$((($(python -c 'from time import time; print int(round(time() * 1000))') - ${NOW})))
  DATA=$(cat /tmp/springmeyer-viz.log)
  if [[ ${CURL_RESULT} != 0 ]]; then
      echo "Failed to call server, got ${DATA}"
      exit $CURL_RESULT
  elif [[ ! ${DATA} =~ "Server-Timing" ]]; then
      echo "Could not detect server-timing headers"
      exit 1
  else
      ( (echo $CURL_TIMINGS | tr "|" "\n" | ./convert.py) && (echo "${DATA}" | ./parse.py) && (echo "overall ${ELAPSED}" )) | termgraph
  fi
}

function loop() {
  local GO=true
  while $GO; do
    sleep .4
    query "$@"
  done
}

function usage() {
  >&2 echo "Usage for viz:"
  >&2 echo ""
  >&2 echo "$ viz [url]"
  >&2 echo ""
  >&2 echo "Options are:"
  >&2 echo ""
  >&2 echo " --loop (run continuously). Example: viz --loop [url]"
  exit 1
}

if [[ -z "$@" ]]; then
  usage
fi

# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
for i in "$@"
do
case $i in
    -h | --help)
    usage
    ;;
    --loop)
    shift
    loop "$@"
    ;;
    *)
    if [[ -z ${1:-} ]]; then
      usage
    fi
    query "$@"
    ;;
esac
done


